### ISSUE TITLE
Build a minimal example of an RPC call in Rust

### ISSUE THREAD

**Issue by edilmedeiros** [edilmedeiros/rust-bcli#3]
Build a minimal example of an RPC call in Rust to understand how to use the [bitcoincore-rpc crate](https://docs.rs/bitcoincore-rpc/0.18.0/bitcoincore_rpc/).

**Comment by itornaza** [comment]
There is a nice example in [rust-bitcoincore-rpc/client/examples/test_against_node.rs](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/1b51e3d0bb614d36d256947f55d228ac0e1dc58f/client/examples/test_against_node.rs )

**Comment by itornaza** [comment]
We can start with creating an rpc client that will be further used to call all API functions like so:

```
// Creates an rpc client used as a base to communicate with the API methods
fn rpc(url: &str, user: &str, passwd: &str) -> Result<(), Error> {
    let url = url.to_string()
    let auth = Auth::UserPass(user.to_string(), passwd.to_string());
    Client::new(url, auth)
}
```

**Comment by edilmedeiros** [comment]
Done with 946a4ec, but waiting for more input from nasser.
